name: MCConquest
version: ${project.version}
main: me.robertle.mcconquest.Core
api-version: 1.13
depend: [Vault, PlaceholderAPI, WorldGuard, EliteLootbox]
authors: [E65]
description: Core plugin for MC Conquest
commands:
  clan:
    description: Base command for MC Conquest clans.
  cc:
    description: Send message to online clan members.
  mcc:
    description: Base command for MC Conquest.
  generator:
    description: Base command for MC Conquest generators.
    aliases: [gen, generators]
  event:
    description: Base command for MC Conquest events.
    aliases: [events]
  coinflip:
    description: Base command for MC Conquest coinflip.
    aliases: [cf]
  war:
    description: Base command for MC Conquest war.
  tag:
    description: Base command for MC Conquest tag.
    aliases: [tags]
  combat:
    description: Base command for MC Conquest.
  special:
    description: Base command for MC Conquest.
  potion:
    description: Base command for MC Conquest.
  food:
    description: Base command for MC Conquest.