name: MCConquest
version: ${project.version}
main: me.robertle.mcconquest.Core
api-version: 1.13
depend: [Vault, PlaceholderAPI, WorldGuard, Companions]
authors: [E65]
description: Core plugin for MC Conquest
commands:
  clan:
    description: Base command for MC Conquest clans.
  cc:
    description: Send message to online clan members.
  mcc:
    description: Base command for MC Conquest.
  generator:
    description: Base command for MC Conquest generators.
    aliases: [gen, generators]
  event:
    description: Base command for MC Conquest events.
    aliases: [events]
  coinflip:
    description: Base command for MC Conquest coinflip.
    aliases: [cf]
  war:
    description: Base command for MC Conquest war.
  tag:
    description: Base command for MC Conquest tag.
    aliases: [tags]
  analyze:
    description: Base command for MC Conquest analyze.
    aliases: [a]
  merchant:
    description: Base command for MC Conquest.
  outpost:
    description: Base command for MC Conquest outpost.
  reboot:
    description: Base command for MC Conquest.
  mcchelp:
    description: Base command for MC Conquest.
  discord:
    description: Base command for MC Conquest.
  wiki:
    description: Base command for MC Conquest.
  donate:
    description: Base command for MC Conquest.
  boss:
    description: Base command for MC Conquest Boss.
  claim:
    description: Base command for MC Conquest.
  shout:
    description: Base command for MC Conquest.
  debuff:
    description: Base command for MC Conquest.
  punish:
    description: Base command for MC Conquest.
  leave:
    description: Base command for MC Conquest.