package me.robertle.mcconquest;

public enum MCCArtifact {
    GUARDIAN_ROD, WITHER_PICKAXE, GIANT_GRINDER, SKELETON_HORSE_LEG,
    SQUID_ROD, PIGMAN_PICKAXE, ZOMBIE_GRINDER, HORSE_LEG, ENDERMAN_EYE,
    WITHER_SKELETON_BONE, COWS_MILK, CAVE_SPIDER_VENOM, BLAZE_SOUL, GOLDEN_APPLE,
    FISHING_ROD, IRON_PICKAXE
}
