package me.robertle.mcconquest;

public enum MCCWeapon {
    DRAGON_SWORD, GIANT_AXE, DRAGON_BOW, GIANT_BOW,
    SQUID_SWORD, GOLEM_AXE, GOLEM_BOW, PIG_SWORD,
    SILVERFISH_AXE, SKELETON_BOW, IRON_SWORD
}
