package me.robertle.mcconquest;

public enum Pet {
    GIANT, DRAGON, HORSE, SKELETON_HORSE, GOLEM, MOOSHROOM, SQUID,
    PIGMAN, BLAZE, POLAR_BEAR, SLIME, PIG, OCELOT, SILVERFISH, SKELETON,
    ENDERMAN, SPIDER, BAT, RABBIT, CHICKEN, WOLF, GHAST, MAGMA_CUBE, GUARDIAN,
    WITCH, SHEEP, ZOMBIE
}
